### ISSUE TITLE
Difference between glyph widths across masters

### ISSUE THREAD

**Issue by asaumierdemers** [TypeNetwork/fb-Decovar#1]
I believe the width of some letters was changed In the last update. See uppercase letter V in terminal B and G. Aren't they supposed to stay the same across masters?

"V" in Decovar-Regular24.ufo = 1280
"V" in Decovar-Regular24TermB.ufo = 1436.0
"V" in Decovar-Regular24TermG.ufo = 1426.0
... (the rest are all equal to default 1280)

**Comment by asaumierdemers** [comment]
I ran a quick script to detect width differences, here's the output:

V [1280, 1280, 1280, 1426.0, 1280, 1280, 1280, 1280, 1436.0, 1280, 1280, 1280, 1280, 1280, 1280]
X [1168, 1168, 1168, 1254, 1168, 1168, 1168, 1168, 1393.0, 1168, 1168, 1168, 1168, 1168, 1168]
RoundDualyNE [653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 659]
K [1163, 1163, 1163, 1208.0, 1163, 1163, 1163, 1163, 1322.0, 1163, 1163, 1163, 1163, 1163, 1163]
W [1636, 1636, 1636, 1802, 1636, 1636, 1636, 1636, 1770.0, 1636, 1636, 1636, 1636, 1636, 1636]
R [994, 994, 994, 1018.0, 994, 994, 994, 994, 1073.0, 994, 994, 994, 994, 994, 994]
A [1274, 1274, 1274, 1423.0, 1274, 1274, 1274, 1274, 1274, 1274, 1274, 1274, 1274, 1274, 1274]
Y [1139, 1139, 1139, 1221.0, 1139, 1139, 1139, 1139, 1312.0, 1139, 1139, 1139, 1139, 1139, 1139]
Allparts [3017, 2332, 3017, 3017, 3017, 3017, 3017, 3017, 3017, 3017, 3017, 3017, 3017, 3017, 3017]

Order is:
[default, TermSkelB, TermSkelA, TermG, TermF, TermE, TermD, TermC, TermB, TermA2, TermA, SkelD4, SkelD2, SkelB2, SkelA]

**Comment by asaumierdemers** [comment]
These are the problematic glyphs:

TermB
Glyphs: X, B, W, R, Y

TermG
Glyphs: X, K, W, R, A, Y

SkelA
Glyphs: RoundDualyNE

TermSkelB
Glyphs: Allparts

**Comment by sannorozco** [comment]
Hallo Alex,

Puches these corrections, thank you!

Still, I ever ever touched RoundDualyNE neither Allparts, so leave them like that.

Let me know.
