### ISSUE TITLE
overlap?

### ISSUE THREAD

**Issue by sberlow** [TypeNetwork/fb-Decovar#11]
![screen shot 2017-03-24 at 4 34 17 pm](https://cloud.githubusercontent.com/assets/7713203/24312623/cc388d56-10af-11e7-97a8-2295edacf3b6.png)
![screen shot 2017-03-24 at 4 33 19 pm](https://cloud.githubusercontent.com/assets/7713203/24312586/a67ded40-10af-11e7-9194-fda1ddaca244.png)

**Comment by dberlow** [comment]
Screen rendering artifact of FontView.

Bug report filed, 5(?) weeks ago.
