### ISSUE TITLE
Rename in name table

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/fb-Decovar#19]
Per @dberlow's comment on https://github.com/google/fonts/pull/656#issuecomment-322340906 please generate a new build with the family name `Decovar Alpha` and filename `DecovarAlpha-VF.ttf` and then tag a release on https://github.com/TypeNetwork/fb-Decovar/releases

**Comment by djrrb** [comment]
Happy to help. Would you like this to replace the existing data in `/fonts`, or exist on a separate branch, or...?

**Comment by dberlow** [comment]
I’m happy to archive What’s there now off-line a type network And fully replace with Alpha-named source and target fonts.

**Comment by davelab6** [comment]
Yes replacing what is in /fonts is fine, git history has the archival
copies.

On Aug 15, 2017 4:47 PM, "dberlow" <notifications@github.com> wrote:

I’m happy to archive What’s there now off-line a type network And fully
replace with Alpha-named source and target fonts.

Sent from my iPad


> On Aug 15, 2017, at 7:26 PM, David Jonathan Ross <notifications@github.com>
wrote:
>
> Happy to help. Would you like this to replace the existing data in
/fonts, or exist on a separate branch, or...?
>
> —
> You are receiving this because you were mentioned.

> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TypeNetwork/fb-Decovar/issues/19#issuecomment-322619612>,
or mute the thread

**Comment by djrrb** [comment]
Ok, done. Does someone besides me want to check and merge my PR (https://github.com/TypeNetwork/fb-Decovar/pull/20)?

**Comment by dberlow** [comment]
Traveling, and I don’t know what a PR is, private release, maybe?

**Comment by davelab6** [comment]
Pull Request

**Comment by davelab6** [comment]
DJR, looks good to merge to me

**Comment by djrrb** [comment]
Thanks! (and safe travels DB!)
