### ISSUE TITLE
Can't Build, Incompatible Glyphs

### ISSUE THREAD

**Issue by michielkauwatjoe** [TypeNetwork/fb-Decovar#27]
Possible duplicate of #23? I'm getting a traceback when trying  to build with the latest FontTools / FontMake:

```
INFO:fontmake.font_project:Building interpolation-compatible TTFs
INFO:fontmake.font_project:Converting curves compatibly
Traceback (most recent call last):
  File "./build.py", line 7, in <module>
    project.run_from_designspace(designspace_path, output=["ttf-interpolatable", "variable"])
  File "/Users/michiel/Code/FontMake/Lib/fontmake/font_project.py", line 438, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/Users/michiel/Code/FontMake/Lib/fontmake/font_project.py", line 492, in run_from_ufos
    ufos, reverse_direction, conversion_error, **kwargs)
  File "/Users/michiel/Code/FontMake/Lib/fontmake/font_project.py", line 198, in build_interpolatable_ttfs
    conversion_error=conversion_error)
  File "/Users/michiel/Code/FontTools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/michiel/Code/FontMake/Lib/fontmake/font_project.py", line 153, in convert_curves
    reverse_direction=reverse_direction, dump_stats=True)
  File "/Users/michiel/Code/Cu2qu/Lib/cu2qu/ufo.py", line 254, in fonts_to_quadratic
    glyphs, cur_max_errors, reverse_direction, stats)
  File "/Users/michiel/Code/Cu2qu/Lib/cu2qu/ufo.py", line 156, in _glyphs_to_quadratic
    raise IncompatibleGlyphsError(*glyphs)
cu2qu.ufo.IncompatibleGlyphsError: 'Allparts'
```

Should I switch to another branch?

**Comment by michielkauwatjoe** [comment]
@petrvanblokland @djrrb @davelab6 @asaumierdemers not sure who is keeping track of Decovar issues; switching branches doesn't seem to make a difference. Here's the script I'm using to build:

```
#!/usr/bin/python

from fontmake.font_project import FontProject

designspace_path = "Decovar.designspace"
project = FontProject()
project.run_from_designspace(designspace_path, output=["ttf-interpolatable", "variable"])
```
(in the `sources` folder). All three libraries have been checked out from git at their latest commit, maybe I should revert them to an older stable version?

**Comment by asaumierdemers** [comment]
@michielkauwatjoe I successfully build from the branch `rearrange-for-build` by running the shell script in `sources/2-build/build.sh`

@djrrb Is this branch ready to merge with master?

**Comment by djrrb** [comment]
I believe it is. I was just waiting for someone other than myself to review
and merge.

**Comment by davelab6** [comment]
Sorry I wasn't able to make time for this. Please merge and I'll file any
issues I find later

**Comment by djrrb** [comment]
@davelab6 done. I’ll close this issue but @michielkauwatjoe feel free to reopen if you still cannot build on the new master branch.

**Comment by davelab6** [comment]
Thank you DJR!

**Comment by michielkauwatjoe** [comment]
@djrrb Thanks! Doesn't seem to build yet when I run fontmake directly in Python, I still have to install the shell version to test the build script. I'll let you know if it works...

**Comment by michielkauwatjoe** [comment]
@djrrb Okay, works fine now!
