### ISSUE TITLE
Website: Make red slider label also grab-able and drag-able

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/fb-Decovar#4]
Per comments on https://news.ycombinator.com/item?id=13619509 I suggest making the red label also grab-able and drag-able :) 

<img width="320" alt="screen shot 2017-02-10 at 22 59 51" src="https://cloud.githubusercontent.com/assets/261579/22851036/b8e53182-efe4-11e6-9d85-fbf40dbc789c.png">

**Comment by dberlow** [comment]
I think right now it's disappearing when someone grabs the bar. 
Do you want it to remain during drag? 
Or is the issue that the bar isn't thick enough?

**Comment by dberlow** [comment]
An interesting forum. Surprised they can type with such bloody eyes.

**Comment by djrrb** [comment]
this is fixed, thanks to @asaumierdemers!

**Comment by davelab6** [comment]
Thanks!!
