### ISSUE TITLE
Time for Decovar

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/fb-Decovar#5]
The enclosed ufo includes three characters A, I and O, that are animate to draw themselves in a generally accepted order. 

So, A,I and O appear to have disappeared in the enclosed, which will be the -1, as the fully drawn glyph will be 1.

Each glyph has a different number of layers, representing the number of intermediates required to draw each glyph.

I, has none, it's a single stroke that draws from top to bottom, and as such it will serve as our control character for time, with the other glyphs on the axis being defined relative to I. We'll get to that after the first prototype.

A has three layers/intermediates, one for each stroke being drawn, and O has 8-9 to approximate the drawing of a curved shape. 

Please make a new axis (DRAW), and see if we can put these together.

Let me know, thanks. 
[Decovar-Regular24Draw1redo.ufo.zip](https://github.com/TypeNetwork/fb-Decovar/files/774265/Decovar-Regular24Draw1redo.ufo.zip)

**Comment by djrrb** [comment]
These are now working in a variable font on the `draw-axis` branch in `3-animation-test` :-)

**Comment by dberlow** [comment]
draw-axis branch in 3-animation-test

comments

1. I is perfect, and will serve as the control for additional axes of same ufo data*.

2. O is 
    a. drawing the two stokes backwards, the 3/4 stroke should draw first, 1/4 second.
    b. there are missing intermediates that need to be added.
    c. there is a boo-boo at 9:30 on the clock.
3. W is good but has little notchkies forming in the crowns

4. A is good, but has one notchky forming in the top crown.

I will try to correct O.

EXCELLENT FIRST TRY!

Note: Please notice that by nature of the process so far, the raw ufo import has put the variation of all of the glyphs on the same range or the draw axis, so that, e.g. the “I” draws really slow, and the W, relatively faster, nearly 4.5 times faster, or so. 

In order to make this word draw with each glyph in order, one at a time, realistically, the average user would never make it to what I’m proposing to set up for them in the axes below

Next Axes: Timed Draw

A. drawing each stroke, with time added to the axis, in the form of nothing happening, in between the strokes of the glyphs.
  1. with “I” as our guide, we define its space, (about 1/8th of the axis?) as 1 second. 
  2. we pad that space with 1/4 of the “I”’s space to allow time between its drawing and the following glpyh.
  3. we define the space on the axis for “A”, as 2 3/4 seconds, (2 for each diagonal, 1/4 space, and 1/2 second for the crossbar). Then add 2 above.
  4. the “W” is 5 seconds, no spaces. Then add 2 above.
  5. the “O” is 4 seconds, with 3 seconds for the long round, 1/2 second for the short round, and 1/2 second in between strokes. Then add 2 above.

Can do?

Then a movie where each letter starts after the last finishes.

**Comment by dberlow** [comment]
Here is a redo of the O, with 16 intermediates and jus tone stroke start to
finish.

Let me know!

thanks.

**Comment by sannorozco** [comment]
yeah! can you post the ufo please? 🙂

**Comment by davelab6** [comment]
(github doesn't accept files as email attachments)

**Comment by djrrb** [comment]
Ok @dberlow: @sannorozco has completed the juggernaut 16-master `DRAW` axis, and I've rewritten the designspace and made a vfont. You can see it in the `draw-axis` branch.

Below are animated gifs showing the `DRAW` axis in action. You'll notice some overlap issues... unfortunately this seems to be related to how Drawbot renders the fonts, and is not something I know how to address while using the vfont as the source.

Of course it's possible to pre-generate the instances and remove overlap from those. But since that's a time-intensive process, I figured we should start here first.

![DRAW 1](https://github.com/TypeNetwork/fb-Decovar/raw/draw-axis/documentation/decovarDRAW.gif)

And one at a time:

![DRAW 2](https://github.com/TypeNetwork/fb-Decovar/raw/draw-axis/documentation/decovarDRAW-oneatatime.gif)
