### ISSUE TITLE
Website: Update URL with skeleton/terminal combination?

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/fb-Decovar#6]
In https://news.ycombinator.com/item?id=13634775 webmaven says,

> it would be nice if the URL reflected the skeleton/terminal combination currently on the screen (and it was bookmark-able)

**Comment by webmaven** [comment]
Hey thanks for filing this issue @davelab6, I didn't realize this repo was also the one for the demo page. :+1:

**Comment by sberlow** [comment]
@davelab6 not sure exactly what this is asking for.
Does this refer to [this Page](https://www.typenetwork.com/brochure/decovar-a-decorative-variable-font-by-david-berlow)

**Comment by davelab6** [comment]
Yes

**Comment by sberlow** [comment]
User story:
as a user I want to be able to select skeleton and terminal options and have the URL designate the coordinate with the instances:

Example:
https://www.typenetwork.com/brochure/decovar-a-decorative-variable-font-by-david-berlow/bifurcated
![bifurcated](https://user-images.githubusercontent.com/7713203/27554195-a0e80418-5a7b-11e7-9ff4-ce93b081ec85.png)

**Comment by webmaven** [comment]
@drrb, any prospects for this being added?

**Comment by asaumierdemers** [comment]
@webmaven this is done now! You might have to wait for the cache to clear before seeing the update.

**Comment by davelab6** [comment]
AMAZING
