### ISSUE TITLE
Weight axis: overlap issue V and A

### ISSUE THREAD

**Issue by sberlow** [TypeNetwork/fb-Decovar#8]
![screen shot 2017-03-24 at 3 12 29 pm](https://cloud.githubusercontent.com/assets/7713203/24309984/6e66f8b2-10a4-11e7-973f-d71c6ee1401a.png)

**Comment by sannorozco** [comment]
Pushed point fixes for these white spaces, now can generate new VF

**Comment by sberlow** [comment]
@asaumierdemers can we regenerate and test?

**Comment by sberlow** [comment]
@sannorozco are these fixed in the M, N, S,V,W,Y?

![screen shot 2017-06-08 at 2 06 33 pm](https://user-images.githubusercontent.com/7713203/26943789-c5da73b2-4c54-11e7-9431-6408c8d65186.png)
![screen shot 2017-06-08 at 2 05 54 pm](https://user-images.githubusercontent.com/7713203/26943794-ca0fd526-4c54-11e7-916c-67abf5780ac4.png)

**Comment by sannorozco** [comment]
It’s fixed for AV, will check for MNSWY

**Comment by davelab6** [comment]
Please check all the named instances are good in Decovar :)

If things go sideways when too many axes are thrown together in some unlikely manner, that's okay for me; the kaleidoscope effect that can sometimes be triggered (especially by buggy renderers that poke holes in overlaps that are winding correctly :) is not a concern for me, in fact it's an opportunity to point out less buddy renderers :)

**Comment by sberlow** [comment]
Will do
@sannorozco is making some fixes to characters it diagonals, 
then we will retest named instances

**Comment by sannorozco** [comment]
Have all corrections done, will be pushing after make a few tests with the new VF.

**Comment by dberlow** [comment]
Thanks!

**Comment by sannorozco** [comment]
Pushed this fix and new builds Decovar-VF.ttf & Decovar-VF.subset.ttf

Let me know!
