### ISSUE TITLE
Weight and Skeleton A Max broken counter form

### ISSUE THREAD

**Issue by sberlow** [TypeNetwork/fb-Decovar#9]
![screen shot 2017-03-24 at 4 37 02 pm](https://cloud.githubusercontent.com/assets/7713203/24312718/30da1676-10b0-11e7-8857-affb94d2bb63.png)

**Comment by sberlow** [comment]
Is this possible to fix, or is it a feature? @sannorozco

**Comment by sannorozco** [comment]
On MaxWeight, these are straight, I guess in your sample, they’re affected by the other activated axis, I don’t think the is possible to fix.

<img width="2163" alt="screen shot 2017-04-05 at 8 52 06 am" src="https://cloud.githubusercontent.com/assets/1184152/24708688/379614b6-19dd-11e7-9e27-b5f1e748901a.png">

**Comment by sberlow** [comment]
thanks, let's close this then

[image: screen shot 2017-04-05 at 8 52 06 am]
